"""Golden-question bake-off (D-020): which Bedrock model answers Q1–Q7 correctly *and* from the data?

For each candidate model, ask the 7 assessment questions in plain English and grade every answer twice:
- correct:  the answer text contains the verified value (from tests/answers/reference.py, pandas)
- grounded: that value appears in the rows of a Cube query the model actually ran (no invented numbers)

Writes docs/bakeoff.md. Run with `make bakeoff` (needs Bedrock access and a running Cube). Costs a few cents.
"""

import re
import sys
import time
import unicodedata
from dataclasses import dataclass
from pathlib import Path

from chat.agent import answer
from chat.cube_client import CubeClient
from chat.models import CANDIDATES, bedrock_runtime
from tests.answers import reference as ref


@dataclass
class Golden:
    qid: str
    question: str
    expected: str  # canonical value that must appear in the answer and in the query rows


def golden_questions() -> list[Golden]:
    weekly = ref.q6_weekly_units()
    return [
        Golden("Q1", "What is the beverage type that Juan drinks the most?", "beer"),
        Golden("Q2", "What is the bar Juan visits the most?", "Yours Truly"),
        Golden("Q3", "What is Juan's favourite beer brand?", "Castle Lite"),
        Golden(
            "Q4",
            "How many times did Juan visit a bar and not have a drink?",
            str(ref.q4_visits_without_drink()),
        ),
        Golden(
            "Q5",
            "How many times has Juan been drunk in the last month?",
            str(len(ref.q5_drunk_days_last_30())),
        ),
        Golden(
            "Q6",
            "On average, how many alcohol units does Juan drink per week, compared with the NHS limit of 14?",
            f"{weekly.mean():.2f}",
        ),
        Golden(
            "Q7",
            "How much money has Juan saved by drinking during happy hours?",
            f"{ref.q7_happy_hour_savings():.2f}",
        ),
    ]


def _normalise(text: str) -> str:
    # NFKC folds the non-breaking spaces/hyphens some models emit (gpt-oss writes "Castle\u202fLite"), then
    # drop markdown emphasis and thousands separators (comma or space).
    text = unicodedata.normalize("NFKC", str(text)).replace("\u2011", "-").replace("*", "")
    text = re.sub(r"\s+", " ", text)
    return re.sub(r"(?<=\d)[, ](?=\d{3}\b)", "", text).lower()  # "21,587.09" / "21 587.09" -> "21587.09"


def _contains_value(text: str, expected: str) -> bool:
    text, expected = _normalise(text), _normalise(expected)
    if re.fullmatch(r"[\d.]+", expected):  # numbers: whole-token match (so "1" doesn't match "14")
        candidates = re.findall(r"\d+(?:\.\d+)?", text)
        return any(abs(float(c) - float(expected)) < 0.005 for c in candidates)
    return expected in text


def _grounded(queries: list[dict], expected: str) -> bool:
    return any(_contains_value(str(q.get("rows", "")), expected) for q in queries)


def run(model_ids: dict[str, str]) -> list[dict]:
    bedrock, cube = bedrock_runtime(), CubeClient()
    results = []
    for label, model_id in model_ids.items():
        for golden in golden_questions():
            start = time.monotonic()
            try:
                turn = answer(golden.question, [], bedrock, model_id, cube)
                text, queries, usage, error = turn.answer, turn.queries, turn.usage, ""
            except Exception as exc:  # noqa: BLE001 - record any failure (access, throttling) as a failed answer
                text, queries, usage, error = "", [], {}, f"{type(exc).__name__}: {exc}"[:200]
            results.append(
                {
                    "model": label,
                    "qid": golden.qid,
                    "expected": golden.expected,
                    "correct": _contains_value(text, golden.expected),
                    "grounded": _grounded(queries, golden.expected),
                    "queries": len(queries),
                    "seconds": round(time.monotonic() - start, 1),
                    "input_tokens": usage.get("inputTokens", 0),
                    "output_tokens": usage.get("outputTokens", 0),
                    "answer": text.replace("\n", " ")[:220],
                    "error": error,
                }
            )
            last = results[-1]
            print(f"{label:38} {golden.qid} correct={last['correct']} grounded={last['grounded']}")
    return results


def write_report(results: list[dict], path: Path = Path("docs/bakeoff.md")) -> None:
    lines = [
        "# Chat model bake-off (golden questions)",
        "",
        "Generated by `make bakeoff` (chat/bakeoff.py). Each model answers Q1–Q7 in plain English",
        "through the Cube tools. **Correct** = the verified value is in the answer. **Grounded** = that",
        "value appears in rows returned by a Cube query the model ran, i.e. not invented.",
        "",
        "| Model | Correct | Grounded | Avg seconds | Input tokens | Output tokens |",
        "|---|---|---|---|---|---|",
    ]
    for model in dict.fromkeys(r["model"] for r in results):
        rows = [r for r in results if r["model"] == model]
        lines.append(
            f"| {model} | {sum(r['correct'] for r in rows)}/{len(rows)} | {sum(r['grounded'] for r in rows)}/"
            f"{len(rows)} | {sum(r['seconds'] for r in rows) / len(rows):.1f} | "
            f"{sum(r['input_tokens'] for r in rows):,} | {sum(r['output_tokens'] for r in rows):,} |"
        )
    lines += ["", "## Answers", "", "| Model | Q | Expected | ✓ | Grounded | Answer / error |"]
    lines.append("|---|---|---|---|---|---|")
    for r in results:
        shown = (r["error"] or r["answer"]).replace("|", "\\|")
        lines.append(
            f"| {r['model']} | {r['qid']} | {r['expected']} | {'✅' if r['correct'] else '❌'} | "
            f"{'✅' if r['grounded'] else '❌'} | {shown} |"
        )
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    selected = {k: v for k, v in CANDIDATES.items() if not sys.argv[1:] or v in sys.argv[1:]}
    write_report(run(selected))
