// Bootstrap a fresh open-source Lightdash without anyone clicking through the UI (AWS deploy).
//
// Lightdash's LD_SETUP_* headless setup is enterprise-only (wired up in ee/index.ts), so on the OSS image this
// uses the same public API the onboarding UI calls, over the internal network:
//   1. no organisation yet -> register a deploy user (POST /api/v1/user) and create the org (PUT /api/v1/org)
//   2. no API token yet    -> log in (POST /api/v1/login) and mint a personal access token
//      (POST /api/v1/user/me/personal-access-tokens)
// State (deploy user's generated password + token) lives in /app/state/lightdash-bot.json, root-only on the
// host. Idempotent: every step is skipped when already done. Prints nothing secret.
const fs = require('fs');
const crypto = require('crypto');

const U = process.env.LIGHTDASH_URL; // internal URL (http://lightdash:8080)
const STATE = '/app/state/lightdash-bot.json';
const state = fs.existsSync(STATE) ? JSON.parse(fs.readFileSync(STATE, 'utf8')) : {};
const save = () => fs.writeFileSync(STATE, JSON.stringify(state), { mode: 0o600 });

async function call(method, path, body, cookie) {
  const res = await fetch(U + path, {
    method,
    headers: {
      'Content-Type': 'application/json',
      // On AWS Lightdash runs with SECURE_COOKIES + TRUST_PROXY (it sits behind Caddy's HTTPS). Express only
      // issues the secure session cookie when the request is HTTPS, so say what Caddy would say.
      'X-Forwarded-Proto': 'https',
      ...(cookie ? { Cookie: cookie } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`${method} ${path} -> ${res.status} ${JSON.stringify(json).slice(0, 200)}`);
  const setCookie = res.headers.getSetCookie?.() || [];
  return { json, cookie: setCookie.map((c) => c.split(';')[0]).join('; ') || cookie };
}

(async () => {
  const health = (await call('GET', '/api/v1/health')).json.results;

  if (health.requiresOrgRegistration) {
    state.email = state.email || `deploy@${process.env.DOMAIN}`;
    state.password = state.password || crypto.randomBytes(24).toString('base64url');
    save(); // persist the password before registering, so a crash can't orphan the account
    let cookie;
    if (!state.registered) {
      try {
        ({ cookie } = await call('POST', '/api/v1/user', {
          firstName: 'Deploy',
          lastName: 'Bot',
          email: state.email,
          password: state.password,
        }));
      } catch (e) {
        // Registered by an earlier, interrupted run: log in with the saved credentials instead.
        ({ cookie } = await call('POST', '/api/v1/login', { email: state.email, password: state.password }));
      }
      state.registered = true;
      save();
    } else {
      // a previous run registered the user but stopped before creating the organisation
      ({ cookie } = await call('POST', '/api/v1/login', { email: state.email, password: state.password }));
    }
    await call('PUT', '/api/v1/org', { name: 'Juan the Drinker' }, cookie);
    console.log('organisation "Juan the Drinker" created with deploy user', state.email);
  } else {
    console.log('organisation already exists');
  }

  if (!state.token) {
    if (!state.password) throw new Error('organisation exists but no deploy-user credentials in state');
    const { cookie } = await call('POST', '/api/v1/login', { email: state.email, password: state.password });
    const pat = await call(
      'POST',
      '/api/v1/user/me/personal-access-tokens',
      { description: 'deploy (lightdash CLI)', autoGenerated: false, expiresAt: null },
      cookie,
    );
    state.token = pat.json.results.token;
    save();
    console.log('API token created for the deploy user');
  } else {
    console.log('API token already present');
  }
})().catch((e) => {
  console.error(`bootstrap failed: ${e.message}`);
  process.exit(1);
});
